In [703]:
import pandas as pd
import numpy as np

In [704]:
wine_df = pd.read_csv('files/wine.csv')

In [705]:
wine_df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [706]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [707]:
wine_df.head(15)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.650,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5
10,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,5
11,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5
12,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.9943,3.58,0.52,9.9,5
13,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.9974,3.26,1.56,9.1,5
14,8.9,0.620,0.18,3.8,0.176,52.0,145.0,0.9986,3.16,0.88,9.2,5

In [708]:
def scale_quality(x):
    return (x - 3) * (10 - 1) / (8 - 3) + 1

wine_df['quality'] = wine_df['quality'].apply(scale_quality)

# y_min_old, y_max_old = 3, 8
# y_min_new, y_max_new = 1, 10
# wine_df['quality'] = wine_df['quality'].map(lambda x: (x - y_min_old) * (y_max_new - y_min_new) / (y_max_old - y_min_old) + y_min_new)

In [709]:
wine_df.head(15)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,4.6
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,4.6
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,4.6
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6.4
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,4.6
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,4.6
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,4.6
7,7.3,0.650,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,8.2
8,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,8.2
9,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,4.6
10,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,4.6
11,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,4.6
12,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.9943,3.58,0.52,9.9,4.6
13,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.9974,3.26,1.56,9.1,4.6
14,8.9,0.620,0.18,3.8,0.176,52.0,145.0,0.9986,3.16,0.88,9.2,4.6

Все данные используются при обучении

In [710]:
X = wine_df.drop("quality", axis=1)
y = wine_df["quality"]

In [711]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

X_train, _X, y_train, _y = train_test_split(X, y, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(_X, _y, train_size=0.5, random_state=42)

scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Удаление одной колонки

In [712]:
from sklearn.linear_model import LinearRegression

features = wine_df.columns

for feature in features:
    if feature != "quality":
        _X = wine_df.drop(feature, axis=1)
        X = _X.drop("quality", axis=1)
        y = wine_df["quality"]
        
        X_train, _X, y_train, _y = train_test_split(X, y, test_size=0.2, random_state=42)
        X_val, X_test, y_val, y_test = train_test_split(_X, _y, train_size=0.5, random_state=42)

        scaler = StandardScaler().fit(X_train)
        X_train_scaled = scaler.transform(X_train)
        X_val_scaled = scaler.transform(X_val)
        X_test_scaled = scaler.transform(X_test)
        
        regression_model = LinearRegression()
        regression_model.fit(X_train_scaled, y_train)
        
        
        regression_val_pred = regression_model.predict(X_val_scaled)
        regression_test_pred = regression_model.predict(X_test_scaled)

        print(f'Without: {feature}')

        print(f'MSE val: {mean_squared_error(y_val, regression_val_pred)}')
        print(f'MAE val: {mean_absolute_error(y_val, regression_val_pred)}')


        print(f'MSE test: {mean_squared_error(y_test, regression_test_pred)}')
        print(f'MAE test: {mean_absolute_error(y_test, regression_test_pred)}')

Without: fixed acidity
MSE val: 1.3653318906699834
MAE val: 0.9414497453531115
MSE test: 1.1648458811607927
MAE test: 0.8721440065342492
Without: volatile acidity
MSE val: 1.440621654010715
MAE val: 0.9683751551077581
MSE test: 1.3066890676136658
MAE test: 0.8989997352490636
Without: citric acid
MSE val: 1.3679825879378977
MAE val: 0.942379351579325
MSE test: 1.166080807509207
MAE test: 0.8721586618138077

Without: residual sugar
MSE val: 1.3684223888109137
MAE val: 0.9427545034181204
MSE test: 1.1643384702267776
MAE test: 0.8719611155814455
Without: chlorides
MSE val: 1.3982483901131881
MAE val: 0.957440762420044
MSE test: 1.1630734441113089
MAE test: 0.8726586226799016
Without: free sulfur dioxide
MSE val: 1.3493198178529555
MAE val: 0.9348513346395425
MSE test: 1.1651908616304965
MAE test: 0.8758730698793237
Without: total sulfur dioxide
MSE val: 1.3477619718263156
MAE val: 0.9409725316729665
MSE test: 1.176013224409707
MAE test: 0.8922345241603065
Without: density
MSE val: 1.3654448084902064
MAE val: 0.9417298227285504
MSE test: 1.1653685940629517
MAE test: 0.8716364401690531
Without: pH
MSE val: 1.3781879879374066
MAE val: 0.9470461783440403
MSE test: 1.1594094729761264
MAE test: 0.8691287765706729
Without: sulphates
MSE val: 1.4405188111844336
MAE val: 0.9736156177774424
MSE test: 1.2429543459835455
MAE test: 0.9007423266358099
Without: alcohol
MSE val: 1.4674997752153929
MAE val: 0.9739953577530613
MSE test: 1.2097495192731127
MAE test: 0.8873112223528278

In [713]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(criterion="friedman_mse", n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

RandomForestRegressor(criterion='friedman_mse', random_state=42)

In [714]:
y_pred = model.predict(X_test_scaled)

t_mse = mean_squared_error(y_test, y_pred)
t_rmse = np.sqrt(mse)
t_mae = mean_absolute_error(y_test, y_pred)

y_pred = model.predict(X_val_scaled)

v_mse = mean_squared_error(y_val, y_pred)
v_rmse = np.sqrt(mse)
v_mae = mean_absolute_error(y_val, y_pred)

print("Model: Random Forest test")
print(f"MSE test: {t_mse}")
print(f"RMSE test: {t_rmse}")
print(f"MAE test: {t_mae}")
print()
print("Model: Random Forest val")
print(f"MSE val: {v_mse}")
print(f"RMSE val: {v_rmse}")
print(f"MAE val: {v_mae}")

Model: Random Forest test
MSE test: 1.0109124
RMSE test: 1.1780548437178409
MAE test: 0.7386750000000014

Model: Random Forest val
MSE val: 1.135287899999999
RMSE val: 1.1780548437178409
MAE val: 0.8082000000000005

In [715]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout

models = {
    'Linear Regression': LinearRegression(),
    'DecisionTree': DecisionTreeRegressor(max_depth=10),
    'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingRegressor(max_depth=25, subsample=0.7, n_estimators=100, random_state=42),
    'Support Vector Regressor': SVR(),
}

k_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dense(32, activation='relu'),
    Dense(64, activation='sigmoid'),
    Dropout(0.2),
    Dense(1)
])
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

k_model.compile(optimizer=optimizer, loss='mean_squared_error')

In [716]:
results = {}
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    
    y_pred = model.predict(X_test_scaled)
    
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    
    results[name + " test"] = {
        'MSE test': mse,
        'RMSE test': rmse,
        'MAE test': mae,
    }
    
    y_pred = model.predict(X_val_scaled)
    
    mse = mean_squared_error(y_val, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_val, y_pred)
    
    results[name + " val"] = {
        'MSE val': mse,
        'RMSE val': rmse,
        'MAE val': mae,
    }

In [717]:
k_model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, verbose=0)

y_pred = k_model.predict(X_test_scaled)

mse_keras = mean_squared_error(y_test, y_pred)
rmse_keras = np.sqrt(mse_keras)
mae_keras = mean_absolute_error(y_test, y_pred)

results['Keras test'] = {
    'MSE test': mse_keras,
    'RMSE test': rmse_keras,
    'MAE test': mae_keras,
}

y_pred = k_model.predict(X_val_scaled)

mse_keras = mean_squared_error(y_val, y_pred)
rmse_keras = np.sqrt(mse_keras)
mae_keras = mean_absolute_error(y_val, y_pred)

results['Keras val'] = {
    'MSE val': mse_keras,
    'RMSE val': rmse_keras,
    'MAE val': mae_keras,
}

5/5 [==============================] - 0s 1ms/step
5/5 [==============================] - 0s 1ms/step

In [718]:
for name, metrics in results.items():
    print(f"Model: {name}")
    for metric, value in metrics.items():
        print(f"{metric}: {value}")
    print()

Model: Linear Regression test
MSE test: 1.2097495192731127
RMSE test: 1.09988613923129
MAE test: 0.8873112223528278

Model: Linear Regression val
MSE val: 1.4674997752153929
RMSE val: 1.2114040511800317
MAE val: 0.9739953577530613

Model: DecisionTree test
MSE test: 2.2643655990931593
RMSE test: 1.5047809139848762
MAE test: 1.0130924290023517

Model: DecisionTree val
MSE val: 2.269169967345238
RMSE val: 1.5063764361358145
MAE val: 1.028804327103803

Model: Random Forest test
MSE test: 1.0174248000000006
RMSE test: 1.0086747741467517
MAE test: 0.7434000000000017

Model: Random Forest val
MSE val: 1.142895824999999
RMSE val: 1.0690630594123056
MAE val: 0.8062875000000002

Model: Gradient Boosting test
MSE test: 0.9325985338130041
RMSE test: 0.9657114133181838
MAE test: 0.6492686131558941

Model: Gradient Boosting val
MSE val: 1.2063408442123653
RMSE val: 1.098335488005539
MAE val: 0.777976645035215

Model: Support Vector Regressor test
MSE test: 1.144472273840354
RMSE test: 1.0698001092916163
MAE test: 0.8187943878608035

Model: Support Vector Regressor val
MSE val: 1.3878132148070663
RMSE val: 1.1780548437178409
MAE val: 0.9074230933587458

Model: Keras test
MSE test: 1.0870969661653729
RMSE test: 1.0426394228904703
MAE test: 0.823790188729763

Model: Keras val
MSE val: 1.3929921866488042
RMSE val: 1.1802508998720587
MAE val: 0.9644019129872323

# Добавление шума

In [719]:
def add_noise(x):
    noise = np.random.uniform(-0.8, 0.8)
    if x == 1:
        return x + abs(noise)
    elif x == 10:
        return x - abs(noise)
    else:
        return x + noise

wine_df['quality'] = wine_df['quality'].apply(add_noise)

In [720]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

X_train, _X, y_train, _y = train_test_split(X, y, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(_X, _y, train_size=0.5, random_state=42)

scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [721]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout

models = {
    'Linear Regression': LinearRegression(),
    'DecisionTree': DecisionTreeRegressor(max_depth=10),
    'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingRegressor(max_depth=25, subsample=0.7, n_estimators=100, random_state=42),
    'Support Vector Regressor': SVR(),
}

k_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dense(32, activation='relu'),
    Dense(64, activation='sigmoid'),
    Dropout(0.2),
    Dense(1)
])
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

k_model.compile(optimizer=optimizer, loss='mean_squared_error')

In [722]:
results = {}
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    
    y_pred = model.predict(X_test_scaled)
    
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    
    results[name + " test"] = {
        'MSE test': mse,
        'RMSE test': rmse,
        'MAE test': mae,
    }
    
    y_pred = model.predict(X_val_scaled)
    
    mse = mean_squared_error(y_val, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_val, y_pred)
    
    results[name + " val"] = {
        'MSE val': mse,
        'RMSE val': rmse,
        'MAE val': mae,
    }

In [723]:
k_model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, verbose=0)

y_pred = k_model.predict(X_test_scaled)

mse_keras = mean_squared_error(y_test, y_pred)
rmse_keras = np.sqrt(mse_keras)
mae_keras = mean_absolute_error(y_test, y_pred)

results['Keras test'] = {
    'MSE test': mse_keras,
    'RMSE test': rmse_keras,
    'MAE test': mae_keras,
}

y_pred = k_model.predict(X_val_scaled)

mse_keras = mean_squared_error(y_val, y_pred)
rmse_keras = np.sqrt(mse_keras)
mae_keras = mean_absolute_error(y_val, y_pred)

results['Keras val'] = {
    'MSE val': mse_keras,
    'RMSE val': rmse_keras,
    'MAE val': mae_keras,
}

5/5 [==============================] - 0s 2ms/step
5/5 [==============================] - 0s 1ms/step

In [724]:
for name, metrics in results.items():
    print(f"Model: {name}")
    for metric, value in metrics.items():
        print(f"{metric}: {value}")
    print()

Model: Linear Regression test
MSE test: 1.2097495192731127
RMSE test: 1.09988613923129
MAE test: 0.8873112223528278

Model: Linear Regression val
MSE val: 1.4674997752153929
RMSE val: 1.2114040511800317
MAE val: 0.9739953577530613

Model: DecisionTree test
MSE test: 2.2379280990931596
RMSE test: 1.4959706210661892
MAE test: 0.9999674290023517

Model: DecisionTree val
MSE val: 2.086919967345238
RMSE val: 1.444617585157137
MAE val: 0.9725543271038031

Model: Random Forest test
MSE test: 1.0174248000000006
RMSE test: 1.0086747741467517
MAE test: 0.7434000000000017

Model: Random Forest val
MSE val: 1.142895824999999
RMSE val: 1.0690630594123056
MAE val: 0.8062875000000002

Model: Gradient Boosting test
MSE test: 0.9325985338130041
RMSE test: 0.9657114133181838
MAE test: 0.6492686131558941

Model: Gradient Boosting val
MSE val: 1.2063408442123653
RMSE val: 1.098335488005539
MAE val: 0.777976645035215

Model: Support Vector Regressor test
MSE test: 1.144472273840354
RMSE test: 1.0698001092916163
MAE test: 0.8187943878608035

Model: Support Vector Regressor val
MSE val: 1.3878132148070663
RMSE val: 1.1780548437178409
MAE val: 0.9074230933587458

Model: Keras test
MSE test: 1.0926059203363476
RMSE test: 1.0452779153585652
MAE test: 0.7812600854039192

Model: Keras val
MSE val: 1.5004584022129563
RMSE val: 1.2249319990158458
MAE val: 0.9508281019330024